### ISSUE TITLE
Switch to by-position-or-by-name as the default calling convention

### ISSUE THREAD

**Issue by jodal** [mopidy/mopidy.js#10]
Mopidy.js 0.4.0 released 2014-06-24 added support for the `by-position-or-by-name` calling convention, but the `by-position-only` calling convention is still the default.

Short term we should change the default. Long term we should remove the `by-position-only` calling convention.

We can change this now, but then we should not bundle the new release of Mopidy.js with Mopidy, so we don't break old clients, ref. mopidy/mopidy#1460.

**Comment by tkem** [comment]
Any idea *which* clients still use `by-position-only`?
Bump Mopidy.js to v1.0, getting rid of this, and continue including 0.4.0 with Mopidy itself until Mopidy v3?

**Comment by jodal** [comment]
I know Mopidy-Musicbox-Webclient just switched in v2.1.0. Other than that, I haven't checked. I agree that this can be changed in Mopidy.js straight away.

**Comment by jodal** [comment]
The `by-position-only` calling convention was removed in commit e50038cfa42ee808ca4d6e815b48be5b8666837f. See the [changelog](https://github.com/mopidy/mopidy.js/blob/master/CHANGELOG.md) for upgrade instructions.
