### ISSUE TITLE
Replace Buster.js with Karma+Mocha

### ISSUE THREAD

**Issue by jodal** [mopidy/mopidy.js#13]
The main advantage of the [Buster.js test framework](http://docs.busterjs.org/) is that the same test suite can be executed both on Node.js and in the browser. I believe the same is achievable with the [Karma test runner](https://karma-runner.github.io/) together with the [Mocha test framework](https://mochajs.org/).

Since Buster.js is barely maintained, Mopidy.js' test suite should be ported to Karma+Mocha.

When doing so, we can either keep [referee](https://www.npmjs.com/package/referee) for assertions through the use of [karma-referee](https://www.npmjs.com/package/karma-referee) or rewrite them to use the [Chai assertion library](http://chaijs.com/).

**Comment by jcass77** [comment]
[Mopidy Musicbox Webclient](https://github.com/pimusicbox/mopidy-musicbox-webclient) has started to use Karma+Mocha+Chai, and may contain a few useful configuration and test script examples to get this started.

**Comment by jodal** [comment]
Mopidy.js' test suite was rewritten from Buster.js to Jest in commit fc1bd39e6251fc7306c200b81d969d6784972830.
