### ISSUE TITLE
Doesn't work with React Native

### ISSUE THREAD

**Issue by simison** [mopidy/mopidy.js#14]
Just tried to `require` Mopidy with [React Native](https://facebook.github.io/react-native/) and hit an issue with [when](https://github.com/cujojs/when) package not working with React Native's package manager.

I solved this by adding following `npm-shrinkwrap.json` to my project:

```json
{
  "dependencies": {
    "when": {
      "version": "3.7.7",
      "from": "when@3.7.7",
      "browser": false
    }
  }
}
```

Read more: https://github.com/cujojs/when/issues/484#issuecomment-257870535

Just something you might want to look into.

**Comment by jodal** [comment]
When.js was replaced by ES6 Promises in commit 23ecc224d642bac0ab5b411acc370906af510348.

It would be great if you could give the master branch a spin on React Native, or at least try it out once 1.0 is released.
