### ISSUE TITLE
mopidy.library.getImages expecting list of URIs validation error

### ISSUE THREAD

**Issue by whomwah** [mopidy/mopidy.js#16]
`"mopidy": "^0.5.0"`

So when calling with:
`mopidy.library.getImages(['spotify:artist:4FCGgZrVQtcbDFEap3OAb2'])`

I get the message:
`Expected a list of URIs, not u\'spotify:artist:4FCGgZrVQtcbDFEap3OAb2\'` back.

Looking at the documentation this looks like the correct way to call the function? Have I understood correctly?

PS I have made the same call with:
`mopidy.library.getImages({ uris: ['spotify:artist:4FCGgZrVQtcbDFEap3OAb2']})`

I don't get an error, but have never got any images back (That could be a `mopidy-spotify` thing.

**Comment by kingosticks** [comment]
It's a subtle one, but if calling by position then it should have been `mopidy.library.getImages([['spotify:artist:4FCGgZrVQtcbDFEap3OAb2']])`

**Comment by kingosticks** [comment]
And I got the following result back from your example.
```
0: {width: 640, __model__: "Image", uri: "https://i.scdn.co/image/6ca555a2eafd568a98f12e24f48448b915d422be", height: 640}
1: {width: 300, __model__: "Image", uri: "https://i.scdn.co/image/60a5515634599dc9bfcffc46baee8865274d7605", height: 300}
2: {width: 64, __model__: "Image", uri: "https://i.scdn.co/image/c701f8d1ff13b972dc180ec8b4e8a279edb4137c", height: 64}
```

**Comment by whomwah** [comment]
@kingosticks firstly thanks for the quick response. You’re right subtle but makes sense. I need to back now and make sure the Mopidy instance I’m talking to is just not slightly out of date.

**Comment by kingosticks** [comment]
Do you think we can close this?
