### ISSUE TITLE
Uncaught ReferenceError: setImmediate is not defined

### ISSUE THREAD

**Issue by weilbith** [mopidy/mopidy.js#30]
Using this within Firefox gives the following error:  `Uncaught ReferenceError: setImmediate is not defined`
According to [these documentation](https://developer.mozilla.org/en-US/docs/Web/API/Window/setImmediate) this is a non-standard feature. In fact most-likely no browser (except MS Edge) supports it.
So I wonder if this problem could be solved using something else like plain `setTimeout`. Thanks for any feedback. :upside_down_face:

**Comment by kingosticks** [comment]
Was wondering why I don't run into this and that's because it was added fairly recently in https://github.com/mopidy/mopidy.js/pull/24 (and I am still using an ancient version of Mopidy.js)

**Comment by weilbith** [comment]
Sorry your message is slightly confusing me. Why is it not happening for you? :thinking:

**Comment by kingosticks** [comment]
Because I'm using an old version of Mopidy.js which does not have the change introduced in #24. The older version I have (in Mopidy-MusicBox-Webclient) does not use `setImmediate`.

**Comment by jodal** [comment]
In PR #31 I've added a `setImmediate()` polyfill. That addition increases the gzipped size of Mopidy.js from 16.25 kB to 19.7 kB, so I'm interested in alternatives.

Using `setTimeout(..., 0)` also passes all current tests. I believe that might delay the events by ~4ms in some browsers. I'm thinking that might be entirely acceptable.

@altano Do you have any thoughts/preferences?

**Comment by altano** [comment]
This is funny: I actually use Firefox as my daily driver but missed this issue because Firefox's websocket implementation is so busted that my app only worked properly in Chrome.

**Comment by jodal** [comment]
Fixed in Mopidy.js 1.1.1 which is on npm now :-)

**Comment by weilbith** [comment]
Thanks a lot for fixing this! :pray:
