### ISSUE TITLE
Feature request: mopidy plugin with mopidy.js

### ISSUE THREAD

**Issue by bluepuma77** [mopidy/mopidy.js#38]
mopidy.js is great as a starter to build an own JS user interface. I think it would be even greater for JS developers to have an example mopidy plugin they can utilize. 

Have a basic mopidy plugin (within examples) which servers the web files within the mopidy process. Only change the plugin name, drop your web files (HTML, CSS, JS, etc) in a dedicated folder, ready to go.

Just an idea...

Cheers
bluepuma

**Comment by jodal** [comment]
I think what we have at https://github.com/mopidy/cookiecutter-mopidy-ext is quite close to what you describe.
