### ISSUE TITLE
Missing event on playback stop

### ISSUE THREAD

**Issue by morgoth** [mopidy/mopidy.js#5]
I'm logging all events, like:
```
mopidy.on(function (ev, args) {
  console.log(ev);
});
```
When `pause` or `play` occurs I get `event:playbackStateChanged`, however when the music is stopped (by ` mopidy.playback.stop()`) I don't get any event.

**Comment by tkem** [comment]
Sorry, cannot reproduce this. When calling `playback.stop()`, I get
```
"websocket:incomingMessage" message { target: WebSocket, isTrusted: true, data: "{"old_state": "playing", "new_state": "stopped", "event": "playback_state_changed"}", origin: "ws://127.0.0.1:6680", lastEventId: "", eventPhase: 0, bubbles: false, cancelable: false, defaultPrevented: false, timeStamp: 1427311224939782, originalTarget: WebSocket } localhost:8100:29:31
"event:playbackStateChanged" Object { old_state: "playing", new_state: "stopped" }
```

What version of Mopidy are you running? Does this behaviour only occur with all tracks, or for example only when playing radio streams?

**Comment by morgoth** [comment]
I'm using Mopidy 0.19.5 (running on Ubuntu) and 0.5.0 version of this js library.
I'm getting `websocket:incomingMessage` event but with: `MessageEvent {ports: Array[0], data: "{"jsonrpc": "2.0", "id": 11, "result": null}", source: null, lastEventId: "", origin: "ws://192.168.1.102:6680"…}`
and still no `event:playbackStateChanged` event

**Comment by morgoth** [comment]
I found another oddity.
When I stop mopidy (by any client) and request the state by `mopidy.playback.getState()` I'm getting `playing`. Obviously there is no music playing, so this state is wrong

**Comment by tkem** [comment]
Should have posted the full trace, starting with the call to `stop`; the message you get is probably the response to `stop()`, as below. Do you get an `event:trackPlaybackEnded`? Can you post the whole trace, including the `stop` message? What does `mpc status` report after you call `stop()`? Anything in the Mopidy server logs?
```
"websocket:outgoingMessage" Object { method: "core.playback.stop", jsonrpc: "2.0", id: 30 } localhost:8100:29:31
"websocket:incomingMessage" message { target: WebSocket, isTrusted: true, data: "{"jsonrpc": "2.0", "id": 30, "result": null}", origin: "ws://192.168.1.3:6680", lastEventId: "", eventPhase: 0, bubbles: false, cancelable: false, defaultPrevented: false, timeStamp: 1427311967254658, originalTarget: WebSocket } localhost:8100:29:31
"websocket:incomingMessage" message { target: WebSocket, isTrusted: true, data: "{"old_state": "playing", "new_state": "stopped", "event": "playback_state_changed"}", origin: "ws://192.168.1.3:6680", lastEventId: "", eventPhase: 0, bubbles: false, cancelable: false, defaultPrevented: false, timeStamp: 1427311967263870, originalTarget: WebSocket } localhost:8100:29:31
"event:playbackStateChanged" Object { old_state: "playing", new_state: "stopped" } localhost:8100:29:31
"websocket:incomingMessage" message { target: WebSocket, isTrusted: true, data: "{"time_position": 0, "tl_track": {"track": {"comment": "http://wien.orf.at/radio/", "album": {"__model__": "Album"}, "__model__": "Track", "name": "Radio Wien 128", "uri": "http://mp3stream17.apasf.apa.at:8000/", "genre": "Pop", "bitrate": 128000}, "__model__": "TlTrack", "tlid": 20}, "event": "track_playback_ended"}", origin: "ws://192.168.1.3:6680", lastEventId: "", eventPhase: 0, bubbles: false, cancelable: false, defaultPrevented: false, timeStamp: 1427311967322528, originalTarget: WebSocket } localhost:8100:29:31
"event:trackPlaybackEnded" Object { time_position: 0, tl_track: Object }
```

**Comment by morgoth** [comment]
That's all I get on "Stop"
```
websocket:outgoingMessage {method: core.playback.stop, jsonrpc: 2.0, id: 10}
websocket:incomingMessage {ports: , data: {"jsonrpc": "2.0", "id": 10, "result": null}, source: null, lastEventId: , origin: ws://192.168.1.102:6680, path: [object NodeList], cancelBubble: false, returnValue: true, srcElement: [object WebSocket], defaultPrevented: false, timeStamp: 1427312751451, cancelable: false, bubbles: false, eventPhase: 2, currentTarget: [object WebSocket], target: [object WebSocket], type: message}
```
I don't get `event:trackPlaybackEnded`

Looking at Mopidy logs, on every command I get something like:
```
2015-03-25 20:47:17,449 WARNING [3195:GMusicBackend-5] py.warnings: /usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py:769: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
```
but not on "stop" - there is no entry in logs when pressing "stop"

mpc output after pressing stop:
```
Andy Jackson - The Boy in the Forest
[playing] #27/33   0:00/7:09 (0%)
volume:  6%   repeat: off   random: off   single: off   consume: off
```
So it looks more like a Mopidy bug, not this js library.
Should I open an issue there?

**Comment by tkem** [comment]
I'd also say it's not a Mopidy.js issue, but something different, probably special to your environment. Have you tried any other backends than gmusic? Is this the same behavior when calling `mpc stop` to stop playback?

**Comment by morgoth** [comment]
I tested with song from local storage and it works properly.
Thanks for investigating. I'll go to gmusic issue tracker as it looks like some bug with this plugin.
I'm not familiar with internals, but looks like there is some "stop" method: https://github.com/hechtus/mopidy-gmusic/blob/develop/mopidy_gmusic/playback.py#L29-L40
