### ISSUE TITLE
when I try to run the example code I get this uncaught syntax error.

### ISSUE THREAD

**Issue by atlantageek** [mopidy/mopidy.js#64]
When I try to run the example code I get this.

Uncaught SyntaxError: Cannot use import statement outside a module (at web.js:4:1)
I've done npm install and npm test seems to run fine.
Then I pointed my browser to the HTML file and got the previous mentioned error.  I also ran a simple python webserver to host the HTML and browsed to the port and got the same error.  I'm trying to open web.html so I can access the console and play with the API.

**Comment by jodal** [comment]
Did you figure out what was wrong?

**Comment by atlantageek** [comment]
No, and honestly I must be doing something stupidly wrong.  How do you normally run the example code. 
1. git checkout
2. npm install
3.run python simple server in the mopidy.js directory
4. Open a browser window to localhost:xxxx/examples/web.html ?
5.
