### ISSUE TITLE
\'unicode\' object has no attribute \'items\

### ISSUE THREAD

**Issue by bencevans** [mopidy/mopidy.js#8]
After getting the `state:online` event and calling...

```js
mopidy.library.search({
  query: 'Newton Faulkner',
}).done(console.log.bind(console))
```

I'm getting this `\'unicode\' object has no attribute \'items\` error sent back...

    Server returned error: { message: 'Application error',
      code: 0,
      data: 
       { message: '\'unicode\' object has no attribute \'items\'',
         traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python2.7/dist-packages/mopidy/internal/jsonrpc.py", line 133, in _handle_single_request\n    result = self._unwrap_result(result)\n  File "/usr/lib/python2.7/dist-packages/mopidy/internal/jsonrpc.py", line 222, in _unwrap_result\n    result = result.get()\n  File "/usr/lib/python2.7/dist-packages/pykka/threading.py", line 52, in get\n    compat.reraise(*self._data[\'exc_info\'])\n  File "/usr/lib/python2.7/dist-packages/pykka/compat.py", line 12, in reraise\n    exec(\'raise tp, value, tb\')\n  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 201, in _actor_loop\n    response = self._handle_receive(message)\n  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 295, in _handle_receive\n    return callee(*message[\'args\'], **message[\'kwargs\'])\n  File "/usr/lib/python2.7/dist-packages/mopidy/core/library.py", line 316, in search\n    query = _normalize_query(query or kwargs)\n  File "/usr/lib/python2.7/dist-packages/mopidy/core/library.py", line 358, in _normalize_query\n    for (field, values) in query.items():\nAttributeError: \'unicode\' object has no attribute \'items\'\n',
         type: 'AttributeError' } }

Is this something server side or am I messing up somewhere?

Cheers,

Ben

**Comment by tkem** [comment]
The `query` parameter is a JS object or Python `dict` mapping search keys to arrays if values.

So you'd have to write

```
mopidy.library.search({ query: {'any': [ 'Newton Faulkner'] } })
```

**Comment by tkem** [comment]
See also https://docs.mopidy.com/en/latest/api/core/#mopidy.core.LibraryController.search

**Comment by bencevans** [comment]
Thank you!!
